In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/shopping.csv')

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
df.head()

,order_id,customer_name,product,category,price,quantity,date,payment_method
0,1,Rahul Sharma,Laptop,Electronics,45000.0,1,2024-01-15,UPI
1,2,Priya Singh,T-Shirt,Clothing,599.0,3,2024-01-16,Credit Card
2,3,Amit Kumar,Headphones,Electronics,2999.0,2,2024-01-16,Debit Card
3,4,Sneha Patel,Jeans,Clothing,1499.0,1,2024-01-17,UPI
4,5,Rohit Verma,Smartphone,Electronics,18999.0,1,2024-01-18,EMI

In [4]:
df.tail()

,order_id,customer_name,product,category,price,quantity,date,payment_method
20,21,Pradeep Nanda,Charger,Electronics,799.0,2,2024-01-30,Debit Card
21,22,Ananya Roy,Kurti,Clothing,699.0,2,2024-01-30,UPI
22,23,Suresh Nair,Laptop,Electronics,45000.0,1,2024-01-21,Debit Card
23,24,Rahul Sharma,Laptop,Electronics,45000.0,1,2024-01-15,UPI
24,25,Vivek Chandra,Webcam,Electronics,NaN,1,2024-02-01,UPI

In [5]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(25, 8)

In [6]:
print("Columns:")
print(df.columns)

Columns:
Index(['order_id', 'customer_name', 'product', 'category', 'price', 'quantity',
       'date', 'payment_method'],
      dtype='str')

In [7]:
print("Data Types:")
print(df.dtypes)

Data Types:
order_id            int64
customer_name         str
product               str
category              str
price             float64
quantity            int64
date                  str
payment_method        str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        25 non-null     int64
 1   customer_name   25 non-null     str
 2   product         25 non-null     str
 3   category        25 non-null     str
 4   price           22 non-null     float64
 5   quantity        25 non-null     int64
 6   date            25 non-null     str
 7   payment_method  25 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.7 KB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        25 non-null     int64
 1   customer_name   25 non-null     str
 2   product         25 non-null     str
 3   category        25 non-null     str
 4   price           22 non-null     float64
 5   quantity        25 non-null     int64
 6   date            25 non-null     str
 7   payment_method  25 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.7 KB

In [10]:
df.describe()

        order_id         price   quantity
count  25.000000     22.000000  25.000000
mean   13.000000  12896.954545   1.520000
std     7.359801  18432.971769   0.822598
min     1.000000    449.000000   1.000000
25%     7.000000    824.000000   1.000000
50%    13.000000   2349.000000   1.000000
75%    19.000000  18249.000000   2.000000
max    25.000000  45000.000000   4.000000

In [11]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
order_id          0
customer_name     0
product           0
category          0
price             3
quantity          0
date              0
payment_method    0
dtype: int64

In [12]:
df.fillna(0, inplace=True)

print("Missing values handled")

Missing values handled

In [13]:
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

In [14]:
df.drop_duplicates(inplace=True)

print("Duplicates Removed")

Duplicates Removed

In [15]:
selected_columns = df[['product', 'price', 'quantity']]

selected_columns.head()

      product    price  quantity
0      Laptop  45000.0         1
1     T-Shirt    599.0         3
2  Headphones   2999.0         2
3       Jeans   1499.0         1
4  Smartphone  18999.0         1

In [16]:
filtered_data = df[df['price'] > 1000]

filtered_data.head()

,order_id,customer_name,product,category,price,quantity,date,payment_method
0,1,Rahul Sharma,Laptop,Electronics,45000.0,1,2024-01-15,UPI
2,3,Amit Kumar,Headphones,Electronics,2999.0,2,2024-01-16,Debit Card
3,4,Sneha Patel,Jeans,Clothing,1499.0,1,2024-01-17,UPI
4,5,Rohit Verma,Smartphone,Electronics,18999.0,1,2024-01-18,EMI
6,7,Vikram Rao,Keyboard,Electronics,1299.0,1,2024-01-19,UPI

In [17]:
df['total_amount'] = df['price'] * df['quantity']

df.head()

,order_id,customer_name,product,category,price,quantity,date,payment_method,total_amount
0,1,Rahul Sharma,Laptop,Electronics,45000.0,1,2024-01-15,UPI,45000.0
1,2,Priya Singh,T-Shirt,Clothing,599.0,3,2024-01-16,Credit Card,1797.0
2,3,Amit Kumar,Headphones,Electronics,2999.0,2,2024-01-16,Debit Card,5998.0
3,4,Sneha Patel,Jeans,Clothing,1499.0,1,2024-01-17,UPI,1499.0
4,5,Rohit Verma,Smartphone,Electronics,18999.0,1,2024-01-18,EMI,18999.0

In [18]:
df.to_csv('../data/cleaned_shopping.csv', index=False)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully